language: node_js
node_js:
  - '14'
before_install:
  - npm install -g firebase-tools
install:
  - npm install
script:
  - npm test || travis_terminate 1;
  - npm run build || travis_terminate 1;
  - firebase deploy --token $CI_TOKEN